### ISSUE TITLE
need a static/profiles folder

### ISSUE THREAD

**Issue by ajman1101** [decause/bizlegfoss#149]

**Comment by ryansb** [comment]
Why?

**Comment by ajman1101** [comment]
This is where students can post their Business profile documents for Remy to read later.

**Comment by liam-middlebrook** [comment]
@ajman1101 perhaps writing a README file for that directory would be a good starting place. (Git won't track the directory unless it has files in it)

**Comment by dropofwill** [comment]
Wouldn't it make more sense to put the profiles up in a wiki format somewhere (maybe even on this repo's wiki since this is effectively a content repo anyways...)? The way I understand it the goal for this class is for future sections to build on the content we create and a wiki is _way_ easier to consume and build upon than a bunch of pdfs in a directory that may or may not be editable or copy/paste-able.

Links to the actual presentations could be included there or in a `static/preso` dir, since their use is pretty tightly coupled with what the people presenting say anyways.

**Comment by liam-middlebrook** [comment]
@ajman1101 what's the status on this? It's been almost a month!

**Comment by Nolski** [comment]
@liam-middlebrook didn't you have a PR that fixed this?

**Comment by liam-middlebrook** [comment]
@Nolski no, but to update everyone else on this issue. I believe that @decause wants people to submit into a GitBook template for HowToFOSS.

**Comment by Nolski** [comment]
@liam-middlebrook @decause SGTM. I'll close this issue for now then.

**Comment by Nolski** [comment]
@decause if this isn't the solution feel free to reopen
